import { Kysely, PostgresDialect, sql } from "kysely";
import pg from "pg";

import { buildConnectionString } from "../app/server/db/connection.ts";
import type {
    Database,
    NewFollower,
    NewTweet,
    NewUser,
    UUID,
} from "../app/server/db/types.ts";
import { buildSeedData } from "./seed-data.ts";
import { loadDotEnv } from "./load-env.ts";

const { Pool } = pg;

loadDotEnv();

interface SeedSummary {
    seed: number;
    users: number;
    tweets: number;
    follows: number;
}

async function clearData(db: Kysely<Database>): Promise<void> {
    await db.transaction().execute(async (trx) => {
        await trx.deleteFrom("followers").execute();
        await trx.deleteFrom("tweets").execute();
        await trx.deleteFrom("users").execute();
    });
}

async function insertUsers(
    db: Kysely<Database>,
    users: NewUser[],
): Promise<Map<string, UUID>> {
    const inserted = await db
        .insertInto("users")
        .values(users)
        .returning(["id", "username"])
        .execute();

    return new Map(inserted.map((user) => [user.username, user.id]));
}

async function insertFollows(
    db: Kysely<Database>,
    follows: NewFollower[],
): Promise<void> {
    if (follows.length === 0) {
        return;
    }

    await db.insertInto("followers").values(follows).execute();
}

async function insertTweetsInIdOrder(
    db: Kysely<Database>,
    tweets: NewTweet[],
): Promise<void> {
    for (const tweet of tweets) {
        await db.insertInto("tweets").values(tweet).execute();
    }
}

function requireUserId(
    userIdsByUsername: Map<string, UUID>,
    username: string,
): UUID {
    const id = userIdsByUsername.get(username);

    if (!id) {
        throw new Error(`Seed data references unknown user "${username}".`);
    }

    return id;
}

async function seed(db: Kysely<Database>): Promise<SeedSummary> {
    const data = buildSeedData({
        seed: Number(process.env.SEED ?? undefined) || undefined,
        generatedUserCount:
            Number(process.env.SEED_USERS ?? undefined) || undefined,
        minTweetsPerUser:
            Number(process.env.SEED_MIN_TWEETS ?? undefined) || undefined,
        maxTweetsPerUser:
            Number(process.env.SEED_MAX_TWEETS ?? undefined) || undefined,
        followsPerUser:
            Number(process.env.SEED_FOLLOWS_PER_USER ?? undefined) ||
            undefined,
    });

    await clearData(db);

    const userIdsByUsername = await insertUsers(db, data.users);

    await insertFollows(
        db,
        data.follows.map((follow) => ({
            follower_id: requireUserId(
                userIdsByUsername,
                follow.followerUsername,
            ),
            followed_id: requireUserId(
                userIdsByUsername,
                follow.followedUsername,
            ),
            created_at: follow.created_at,
        })),
    );

    await insertTweetsInIdOrder(
        db,
        data.tweets.map((tweet) => ({
            author_id: requireUserId(userIdsByUsername, tweet.authorUsername),
            text: tweet.text,
            created_at: tweet.created_at,
        })),
    );

    return {
        seed: data.seed,
        users: data.users.length,
        tweets: data.tweets.length,
        follows: data.follows.length,
    };
}

async function run(): Promise<void> {
    const pool = new Pool({
        connectionString: buildConnectionString(),
    });

    const db = new Kysely<Database>({
        dialect: new PostgresDialect({ pool }),
    });

    try {
        const summary = await seed(db);
        const tableCounts = await sql<{
            users: string;
            tweets: string;
            follows: string;
        }>`
            SELECT
                (SELECT count(*) FROM users) AS users,
                (SELECT count(*) FROM tweets) AS tweets,
                (SELECT count(*) FROM followers) AS follows
        `.execute(db);

        const counts = tableCounts.rows[0];

        console.log(`Seed: ${summary.seed}`);
        console.log(`Users: ${counts.users}`);
        console.log(`Tweets: ${counts.tweets}`);
        console.log(`Follows: ${counts.follows}`);
        console.log(
            "UUID fixture extension: reserved Postgres uuidv7 pool, not generated by default.",
        );
    } finally {
        await db.destroy();
    }
}

run().catch((error: unknown) => {
    console.error(error);
    process.exit(1);
});
